# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre del programa')),
                ('codigo', models.CharField(max_length=4, verbose_name='código del programa')),
                ('nivel_academico', models.CharField(choices=[('Pregrado', 'Pregrado'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=10, verbose_name='nivel académico')),
            ],
            options={
                'ordering': ('nombre',),
                'permissions': (('gestionar_programas', 'Gestionar programas'),),
            },
        ),
    ]
