# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='responsables',
            field=models.ManyToManyField(related_name='programas_es_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Seleccione los directores encargados de dirigir el programa académico'),
        ),
    ]
