# Generated by Django 3.2.15 on 2022-09-27 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_auto_20220919_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['numeracion', 'contenido', 'actividad', 'restriccion_nivel_actividad']},
        ),
        migrations.RenameField(
            model_name='calificacioncualitativa',
            old_name='valor_numerico',
            new_name='valor_minimo',
        ),
        migrations.AlterField(
            model_name='nota',
            name='resultado',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Resultado cuantitativo de la respuesta'),
        ),
    ]
