# Generated by Django 3.2.15 on 2022-09-27 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_auto_20220927_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncualitativa',
            name='valor_maximo',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valor numérico máximo asociado a esta calificación cuantitativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacioncualitativa',
            name='valor_minimo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valor numérico mínimo asociado a esta calificación cuantitativa'),
        ),
    ]
