# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorcursoprograma',
            name='curso_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor_curso_programa_asociados', to='cursos.cursodelprograma', verbose_name='Curso del programa'),
        ),
    ]
