# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periodos_academicos', '0001_initial'),
        ('competencias', '0002_profesorcursoprograma_curso_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorcursoprograma',
            name='estudiantes_asignados',
            field=models.ManyToManyField(related_name='profesor_curso_programa_asociados_a_estudiante', through='competencias.Grupo', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes asignados a este profesor de un curso del programa'),
        ),
        migrations.AddField(
            model_name='profesorcursoprograma',
            name='niveles_evaluacion',
            field=models.ManyToManyField(related_name='profesor_curso_programa_asociado_a_niveles_evaluacion', through='competencias.RestriccionNivelProfesorCurso', to='competencias.NivelEvaluacion', verbose_name='Niveles de evaluación asociados'),
        ),
        migrations.AddField(
            model_name='profesorcursoprograma',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor_curso_programa_asociados', to='periodos_academicos.periodoacademico', verbose_name='Periodo académico'),
        ),
        migrations.AddField(
            model_name='profesorcursoprograma',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor_curso_programa_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='nivelevaluacion',
            name='curso_del_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles_evaluacion_asociados', to='cursos.cursodelprograma', verbose_name='Curso del programa'),
        ),
        migrations.AddField(
            model_name='nivelevaluacion',
            name='metas_curso_del_programa',
            field=models.ManyToManyField(related_name='metas_niveles_evaluacion_asociados', through='competencias.MetaObjetivo', to='cursos.CursoDelPrograma', verbose_name='Curso del programa asociados a metas en este novel de evaluación'),
        ),
        migrations.AddField(
            model_name='nivelevaluacion',
            name='nivel_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_niveles_evaluacion', to='competencias.nivelevaluacion', verbose_name='Nivel padre'),
        ),
        migrations.AddField(
            model_name='nivelevaluacion',
            name='tipo_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles_evaluacion_asociados', to='competencias.tiponivelevaluacion', verbose_name='Tipo nivel evaluación'),
        ),
        migrations.AddField(
            model_name='metaobjetivo',
            name='curso_del_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_ascociadas', to='cursos.cursodelprograma', verbose_name='Curso del programa asociado las metas de un nivel de evaluación'),
        ),
        migrations.AddField(
            model_name='metaobjetivo',
            name='nivel_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_ascociadas', to='competencias.nivelevaluacion', verbose_name='Nivel de evaluacion asociado las metas de un curso del programa'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante de un curso de programa'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor_curso_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_asociados', to='competencias.profesorcursoprograma', verbose_name='Profesor de un curso de programa'),
        ),
    ]
