# Generated by Django 3.2.15 on 2022-09-20 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencias', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['profesor_curso_programa', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='profesorcursoprograma',
            name='estudiantes_asignados',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='grupo',
            name='estudiante',
            field=models.ManyToManyField(related_name='grupos_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante de un curso de programa'),
        ),
    ]
