# Generated by Django 3.2.15 on 2022-09-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_auto_20220920_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='estudiante',
            new_name='estudiantes',
        ),
    ]
