# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('aprobada', models.BooleanField(null=True)),
                ('curso_del_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_del_cursoprograma', to='cursos.cursodelprograma')),
            ],
            options={
                'ordering': ['periodo_academico'],
                'permissions': (('gestionar_matriculas', 'Matriculas - Gestionar'),),
            },
        ),
    ]
