# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periodos_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_del_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodos_academicos.periodoacademico'),
        ),
    ]
