# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código del curso')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoDelPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_del_curso', to='cursos.curso')),
                ('prerrequisito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguientes_cursos_del_programa', to='cursos.cursodelprograma')),
            ],
            options={
                'ordering': ('programa', 'curso'),
            },
        ),
    ]
