# Generated by Django 3.2.15 on 2022-09-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodelprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_del_programa', to='programas.programa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='programas',
            field=models.ManyToManyField(through='cursos.CursoDelPrograma', to='programas.Programa'),
        ),
    ]
